# COMANDOS LINUX

In [1]:
!ls

sample_data


In [2]:
!pwd

/content


In [3]:
!pip freeze

absl-py==1.4.0
accelerate==1.2.1
aiohappyeyeballs==2.4.4
aiohttp==3.11.11
aiosignal==1.3.2
alabaster==1.0.0
albucore==0.0.19
albumentations==1.4.20
altair==5.5.0
annotated-types==0.7.0
anyio==3.7.1
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array_record==0.6.0
arviz==0.20.0
astropy==6.1.7
astropy-iers-data==0.2025.1.6.0.33.42
astunparse==1.6.3
async-timeout==4.0.3
atpublic==4.1.0
attrs==24.3.0
audioread==3.0.1
autograd==1.7.0
babel==2.16.0
backcall==0.2.0
beautifulsoup4==4.12.3
bigframes==1.31.0
bigquery-magics==0.5.0
bleach==6.2.0
blinker==1.9.0
blis==0.7.11
blosc2==2.7.1
bokeh==3.6.2
Bottleneck==1.4.2
bqplot==0.12.44
branca==0.8.1
CacheControl==0.14.2
cachetools==5.5.0
catalogue==2.0.10
certifi==2024.12.14
cffi==1.17.1
chardet==5.2.0
charset-normalizer==3.4.1
chex==0.1.88
clarabel==0.9.0
click==8.1.8
cloudpathlib==0.20.0
cloudpickle==3.1.0
cmake==3.31.2
cmdstanpy==1.2.5
colorcet==3.1.0
colorlover==0.3.0
colour==0.1.5
community==1.0.0b1
confection==0.1.5
cons==0.4.6
contourpy==1

# IMPORTAR LIBRERIA

In [7]:
import numpy as np

# CONVERTIENDO LISTAS EN ARRAYS DE NUMPY

In [4]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
type(lista)

list

In [8]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(arr)

numpy.ndarray

# SLICING

In [10]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [11]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

# TIPO DE DATOS EN NUMPY

In [12]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [13]:
arr_float = np.array([1,2,3,4], dtype='float64')
arr_float.dtype

dtype('float64')

# CAST DE TIPO DE DATOS

In [14]:
arr = np.array([0,1,2,3,4])
arr_bool = arr.astype(np.bool_)
arr_bool.dtype

dtype('bool')

In [15]:
arr_bool

array([False,  True,  True,  True,  True])

In [16]:
arr_string = np.array([0,1,2,3,4])
arr_string = arr.astype(np.string_)
arr_string

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')