# **GENERACIÓN DE DATOS ALEATORIOS**

In [1]:
import numpy as np

# ARANGE

In [2]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# ZEROS

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# ONES

In [7]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# EYE

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# LINSPACE

In [4]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# RANDOM

In [5]:
np.random.rand()

0.357595728746397

In [8]:
np.random.rand(4)

array([0.80631887, 0.89127684, 0.61749545, 0.1981191 ])

In [9]:
np.random.rand(4,4)

array([[0.87066798, 0.75124946, 0.51431255, 0.23296254],
       [0.48152453, 0.15016098, 0.63398453, 0.38642961],
       [0.05410647, 0.36539895, 0.26903868, 0.78128153],
       [0.09505251, 0.42890723, 0.56301911, 0.38081994]])

In [10]:
np.random.randint(1,100,(10,10))

array([[26, 24, 57, 38, 52, 50, 43,  6, 60, 61],
       [26, 72, 21, 41, 70, 40, 63, 45, 41,  2],
       [68, 85, 76, 25, 36, 86, 70, 56, 18, 85],
       [47, 63, 13,  6, 66, 38, 33, 33, 53, 40],
       [63, 77, 57, 77, 49, 66, 80, 58, 41, 48],
       [74, 83, 33, 17, 60, 57, 38, 57, 80, 25],
       [50, 14, 39, 24, 56, 74, 22, 59, 81, 30],
       [58, 95,  3, 32, 64, 57, 55, 40, 31, 48],
       [27, 89, 88, 67, 19, 64, 63, 37, 66, 41],
       [ 1, 90, 84, 83, 64,  4, 32, 40, 59, 36]])