# **FUNCIONES MAS COMUNES DE NUMPY**

In [1]:
import numpy as np

# SHAPE Y RESHAPE

In [2]:
arr = np.random.randint(1,10,(3,2))
arr

array([[7, 2],
       [3, 1],
       [7, 7]])

In [3]:
arr.shape

(3, 2)

In [5]:
arr.ndim

2

In [4]:
arr.reshape(1,6)

array([[7, 2, 3, 1, 7, 7]])

In [6]:
arr.ndim

2

# MAX Y ARGMAX

In [7]:
arr = np.random.randint(1,20,10)
arr

array([12,  9, 15,  7, 10, 19,  3,  5,  7,  6])

In [8]:
matriz = arr.reshape(2,5)
matriz

array([[12,  9, 15,  7, 10],
       [19,  3,  5,  7,  6]])

In [9]:
arr.max()

19

In [10]:
matriz.max()

19

In [11]:
matriz.max(1)

array([15, 19])

In [12]:
arr.argmax()

5

# MIN Y ARGMIN

In [13]:
arr.min()

3

In [14]:
arr.argmin()

6

In [15]:
matriz.min(0)

array([12,  3,  5,  7,  6])

# SORT

In [16]:
arr

array([12,  9, 15,  7, 10, 19,  3,  5,  7,  6])

In [19]:
arr.sort()
arr

array([ 3,  5,  6,  7,  7,  9, 10, 12, 15, 19])

# MEDIAM

In [21]:
np.median(arr)

8.0

# DESVIACIÓN STANDARD STD

In [22]:
np.std(arr)

4.627094120503711

# VARIANZA VAR

In [23]:
np.var(arr)

21.410000000000004